# Generated by Django 5.0.4 on 2024-04-23 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated_at')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.basemodel')),
                ('student_id', models.CharField(blank=True, max_length=225, null=True, unique=True, verbose_name='student_id')),
                ('name', models.CharField(blank=True, max_length=225, null=True, verbose_name='student_name')),
                ('department', models.CharField(blank=True, max_length=50, null=True, verbose_name='department')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='student_image')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcode', verbose_name='qrcode')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
            },
            bases=('myapp.basemodel',),
        ),
    ]
