# Generated by Django 5.0.4 on 2024-04-24 11:30

import apps.myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PDF_FILES', models.FileField(blank=True, null=True, upload_to='pdf_files', verbose_name='pdf_files')),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
            },
        ),
        migrations.AlterField(
            model_name='students',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.myapp.models.image_path, verbose_name='student_image'),
        ),
    ]
